services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SchulIT\CommonBundle\Controller\LogController:
        tags:
            - 'controller.service_arguments'

    SchulIT\CommonBundle\Controller\DarkModeController:
        tags:
            - 'controller.service_arguments'

    SchulIT\CommonBundle\Controller\AutoconfigController:
        tags:
          - 'controller.service_arguments'

    SchulIT\CommonBundle\Controller\LogoutController:
        arguments:
            $logoutUrl: '%env(IDP_LOGOUT_URL)%'
